import {
  DEFAULT_KDF_COST,
  decryptMessage,
  deriveWrappingKey,
  fromHex,
  toHex,
  unwrapIdentity,
  verifyFrankingSignature,
} from '@/lib/crypto/core';

/** Material the web client actually produced, checked in as literals.
 *
 *  Two jobs at once. It is the same guard the web suite carries — every other
 *  test here encrypts and decrypts with the same build, so an upgrade to
 *  @noble that changed the wire format on both sides would pass all of them
 *  and make every stored message unreadable on deploy. And because these exact
 *  bytes came off the *other* client, it is also the only test in the project
 *  that proves a message written on the web opens on a phone.
 *
 *  Generated by @noble/ciphers and @noble/curves 2.3.0, the versions in
 *  production before the bump that introduced this file.
 *
 *  If this fails after a dependency bump, do not regenerate the fixtures. It
 *  means stored messages no longer decrypt, and the upgrade needs a migration
 *  rather than a new fixture. */
const STORED = {
  recipientPrivate: '819042064ed81113a195a37ecebe0e941a15a2d9536d5f8d96a4f85ae26c5cfb',
  recipientPublic: '1438c939baa0d552a2c3251a2e28afd0b74a792bda42b10078f8dca6f7ebda4c',
  senderSigningPublic: 'e6970eae66f182ce243c3706a8317839c4f9fbec39270f83a742e7f3ad84d037',
  clientNonce: '11111111-1111-4111-8111-111111111111',
  ciphertext:
    '47a0b9d273c12f5736176451e909960031e102b1571f8612748fa560547165c0' +
    '458f515b090dc2cb913c92fb6495e27cd17d5832aded5679196252595802b048' +
    '3af16d9fc134ce8fece24024b26d35fd8f65d523dcf4ae0b',
  nonce: '9741e3e703835b3dfec8d888',
  senderEphemeral: '4661b3b6b2f19b17d30c660e46bedd5ef5e6d48a26fd1dd49d1bc1761f01ac75',
  senderCopy:
    '4c86fda26b67662bd5cc1dffb607a2c9ac8912deee294e0c22f16c72e040ad1d' +
    '555accde4152a90502951ba1db794095',
  frankingCommitment: '6908752814eae5c0f8b59b162c08f224373ef87800e01880e420adbb5a48f873',
  frankingSignature:
    '3e1b734bbd9c72506871c699c3af02fe1fa0ca06c870d64f3203f21999f15f60' +
    '4eebbfa2c2cba0708e02d6d1d5df63af2afb15edb45b89efeeca33cb21feac07',
  wrappedIdentity:
    '5a3657f272ab64a98613b2fc46f4ea5147eadbb7de12237e5532bf31c8def504' +
    '0d941cbe33d12838ba165fe546f51281569e3c447a24abe10f40e616b8fcd643' +
    '6041669d0732f1a661b6a00383226562df1922d5ebcf602f376a9f53',
  wrapSalt: '00112233445566778899aabbccddeeff',
} as const;

const PLAINTEXT = 'Bună, ăsta e un mesaj de test — 🎬';

describe('material stored by an earlier release', () => {
  it('still decrypts, with its franking commitment intact', () => {
    const opened = decryptMessage(
      {
        ciphertext: fromHex(STORED.ciphertext),
        nonce: fromHex(STORED.nonce),
        senderEphemeralKey: fromHex(STORED.senderEphemeral),
        senderCopy: fromHex(STORED.senderCopy),
        frankingCommitment: fromHex(STORED.frankingCommitment),
        frankingSignature: fromHex(STORED.frankingSignature),
      },
      fromHex(STORED.recipientPrivate),
    );

    expect(opened.plaintext).toBe(PLAINTEXT);
    expect(opened.commitmentVerified).toBe(true);
  });

  it('still verifies as written by the account that signed it', () => {
    expect(
      verifyFrankingSignature(
        fromHex(STORED.frankingCommitment),
        fromHex(STORED.frankingSignature),
        fromHex(STORED.senderSigningPublic),
        STORED.clientNonce,
      ),
    ).toBe(true);
  });

  it('still unwraps a key backup written by the other client', () => {
    const wrappingKey = deriveWrappingKey(
      'correct horse battery staple',
      fromHex(STORED.wrapSalt),
      DEFAULT_KDF_COST,
    );
    const identity = unwrapIdentity(fromHex(STORED.wrappedIdentity), wrappingKey);

    expect(toHex(identity.exchangePrivateKey)).toBe(STORED.recipientPrivate);
    expect(toHex(identity.exchangePublicKey)).toBe(STORED.recipientPublic);
  });
});
