FROM rust:1.78-slim
RUN apt-get update && apt-get install -y pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*
RUN cargo install cargo-watch sqlx-cli --no-default-features --features postgres
WORKDIR /app
COPY . .
CMD ["cargo-watch", "-x", "run"]
